<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ArticulosSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('articulos')->insert([
            [
                'nombre' => 'Camiseta Titular River Plate 2023',
                'descripcion' => 'AUTHENTIC RIVER PLATE 23/24',
                'precio' => 55900.00,
                'talle_id' => 1,
                'imagen' => 'productos-actualizados/6732955740576_camiseta1.PNG',
                'imagen_hover' => 'productos-actualizados/672fd6d8d8464_camiseta1-atras.png',
                'fecha_creacion' => '2024-01-01',
                'categoria_id' => 10,
                'cantidad' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Camiseta Suplente River Plate 2023',
                'descripcion' => 'AUTHENTIC RIVER PLATE 23/24',
                'precio' => 55900.00,
                'talle_id' => 1,
                'imagen' => 'productos/camiseta2.PNG',
                'imagen_hover' => 'productos/camiseta2-atras.png',
                'fecha_creacion' => '2024-01-01',
                'categoria_id' => 10,
                'cantidad' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Camiseta Arquero River Plate 2023',
                'descripcion' => 'AUTHENTIC RIVER PLATE 23/24',
                'precio' => 72000.00,
                'talle_id' => 1,
                'imagen' => 'productos/camiseta3.PNG',
                'imagen_hover' => 'productos/camiseta3-atras.png',
                'fecha_creacion' => '2024-01-01',
                'categoria_id' => 10,
                'cantidad' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Campera Oficial River Plate 2023',
                'descripcion' => 'AUTHENTIC RIVER PLATE 23/24',
                'precio' => 35000.00,
                'talle_id' => 1,
                'imagen' => 'productos/camiseta4.PNG',
                'imagen_hover' => 'productos/camiseta4-atras.png',
                'fecha_creacion' => '2024-01-01',
                'categoria_id' => 11,
                'cantidad' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Buzo Oficial River Plate 2023',
                'descripcion' => 'AUTHENTIC RIVER PLATE 23/24',
                'precio' => 32000.00,
                'talle_id' => 1,
                'imagen' => 'productos/camiseta5.PNG',
                'imagen_hover' => 'productos/camiseta5-atras.png',
                'fecha_creacion' => '2024-01-01',
                'categoria_id' => 12,
                'cantidad' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Remera Oficial River Plate 2023',
                'descripcion' => 'AUTHENTIC RIVER PLATE 23/24',
                'precio' => 15000.00,
                'talle_id' => 1,
                'imagen' => 'productos/camiseta6.PNG',
                'imagen_hover' => 'productos/camiseta6-atras.png',
                'fecha_creacion' => '2024-01-01',
                'categoria_id' => 13,
                'cantidad' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Camiseta Titular River Plate 2024',
                'descripcion' => 'AUTHENTIC RIVER PLATE 24/25',
                'precio' => 124000.00,
                'talle_id' => 1,
                'imagen' => 'productos/camiseta7.jpg',
                'imagen_hover' => 'productos/camiseta7-atras.jpg',
                'fecha_creacion' => '2024-01-01',
                'categoria_id' => 10,
                'cantidad' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Camiseta Suplente River Plate 2024',
                'descripcion' => 'AUTHENTIC RIVER PLATE 24/25',
                'precio' => 100000.00,
                'talle_id' => 1,
                'imagen' => 'productos/camiseta8.jpg',
                'imagen_hover' => 'productos/camiseta8-atras.jpg',
                'fecha_creacion' => '2024-01-01',
                'categoria_id' => 10,
                'cantidad' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Camiseta Arquero River Plate 2024',
                'descripcion' => 'AUTHENTIC RIVER PLATE 24/25',
                'precio' => 80000.00,
                'talle_id' => 1,
                'imagen' => 'productos/camiseta9.jpg',
                'imagen_hover' => 'productos/camiseta9-atras.jpg',
                'fecha_creacion' => '2024-01-01',
                'categoria_id' => 10,
                'cantidad' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Campera Oficial River Plate 2024',
                'descripcion' => 'AUTHENTIC RIVER PLATE 24/25',
                'precio' => 76000.00,
                'talle_id' => 1,
                'imagen' => 'productos/camiseta10.jpg',
                'imagen_hover' => 'productos/camiseta10-atras.jpg',
                'fecha_creacion' => '2024-01-01',
                'categoria_id' => 11,
                'cantidad' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Buzo Oficial River Plate 2024',
                'descripcion' => 'AUTHENTIC RIVER PLATE 24/25',
                'precio' => 40000.00,
                'talle_id' => 1,
                'imagen' => 'productos/camiseta11.jpg',
                'imagen_hover' => 'productos/camiseta11-atras.jpg',
                'fecha_creacion' => '2024-01-01',
                'categoria_id' => 12,
                'cantidad' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Remera Oficial River Plate 2024',
                'descripcion' => 'AUTHENTIC RIVER PLATE 24/25',
                'precio' => 25000.00,
                'talle_id' => 1,
                'imagen' => 'productos/camiseta12.jpg',
                'imagen_hover' => 'productos/camiseta12-atras.jpg',
                'fecha_creacion' => '2024-01-01',
                'categoria_id' => 13,
                'cantidad' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Short Suplente River Plate 2024',
                'descripcion' => 'AUTHENTIC RIVER PLATE 24/25',
                'precio' => 21000.00,
                'talle_id' => 1,
                'imagen' => 'productos/camiseta13.jpg',
                'imagen_hover' => 'productos/camiseta13-atras.jpg',
                'fecha_creacion' => '2024-01-01',
                'categoria_id' => 14,
                'cantidad' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Short Jugador River Plate 2024',
                'descripcion' => 'AUTHENTIC RIVER PLATE 24/25',
                'precio' => 21000.00,
                'talle_id' => 1,
                'imagen' => 'productos/camiseta14.jpg',
                'imagen_hover' => 'productos/camiseta14-atras.jpg',
                'fecha_creacion' => '2024-01-01',
                'categoria_id' => 14,
                'cantidad' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Short Arquero River Plate 2024',
                'descripcion' => 'AUTHENTIC RIVER PLATE 24/25',
                'precio' => 20000.00,
                'talle_id' => 1,
                'imagen' => 'productos/camiseta15.jpg',
                'imagen_hover' => 'productos/camiseta15-atras.jpg',
                'fecha_creacion' => '2024-01-01',
                'categoria_id' => 14,
                'cantidad' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'nombre' => 'Calza Running 2024',
                'descripcion' => 'Calza para actividad fisica',
                'precio' => 20000.00,
                'talle_id' => 2,
                'imagen' => 'productos-actualizados/camiseta16.jpg',
                'imagen_hover' => 'productos-actualizados/camiseta16-atras.jpg',
                'fecha_creacion' => '2024-03-28',
                'categoria_id' => 15,
                'cantidad' => 1,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
